evangelischeomroep/nietalleen

- pages/index.vue
Wanneer deze PR wordt gemerged, dan wordt het emailadres toegevoegd als optie om contact op te nemen ipv alleen bellen
> add emailadres to homepage

- components/HelpersMap.vue
Wanneer deze PR wordt gemerged, ...
...
> fix weird way of rendering the map of helpers

- pages/hulp-bieden.vue
- pages/index.vue
- pages/over.vue
Wanneer deze PR wordt gemerged,
... zijn de openingstijden vernieuwd
... is Compassion toegevoegd op de /over pagina
... is de typfout 'plaatsnaan' weg op de /over pagina
... is _Stichting HipHelpt_ nu _HipHelpt_ op de /over pagina.
zie netlify-linkje
> NAL-60 Tekstaanpassingen

- components/FooterContent.vue
- layouts/default.vue
- pages/over.vue
> NAL-35 testmerge naar develop

- components/FooterContent.vue
- layouts/default.vue
- pages/over.vue
Wanneer deze PR wordt gemerged, zullen de juridische linkjes in de footer zijn verreikt met popupjes die context en uitleg geven waarom de EO hier wordt genoemd.
https://develop-www.nietalleen.nl/
Vervolgens onderaan in de footer op de verschillende linkjes klikken
> NAL-35 Extra uitleg bij juridische linkjes

- components/HelpersMap.vue
- components/NeedHelpForm.vue
- pages/hulp-bieden.vue
- pages/over.vue
Wanneer deze PR wordt gemerged, staat alles net een beetje mooier.
Wat met name opvalt is dat Google Maps is nu op desktop niet meer de volledige breedte is.
Zie netlify linkje
> Visuele bugfixjes van NAL-57 | NAL-67 | NAL-65

- pages/index.vue
Deelnemers op de homepage van 490 naar 756
> Up the number of participants on the homepage

- layouts/default.vue
Wanneer deze PR wordt gemerged, heeft de website zowaar een hamburgermenu!
Zie deploy-linkje van Netlify.
> NAL-64 toevoegen van hamburgermenu

- README.md
Wanneer deze PR wordt gemerged, dan wordt de readme bijgewerkt
...
> updated readme with #Nietalleen data

- layouts/default.vue
- pages/index.vue
Wanneer deze PR wordt gemerged, dan staat er een extra tekst bij de hulp krijgen pagina die werkt als disclaimer
Check of de tekst er staat in de deployy preview
> NAL-87 add a disclaimer text to the homepage

- components/FooterContent.vue
- layouts/default.vue
Wanneer deze PR wordt gemerged, is er op elke pagina een prefooter met linkjes naar de Facebook en Twitter van #nietalleen
Zie netlify-deploy preview linkje.
> NAL-42 a prefooter with social links

- components/NeedHelpForm.vue
- pages/hulp-bieden.vue
- pages/index.vue
Wanneer deze PR wordt gemerged, worden de tekstuele wijzigingen zoals verzameld in NAL-111 online gezet.
- https://5e7b02e5e381580009815f24--nietalleen.netlify.com/
> NAL-111: Tekstuele wijzigingen van woensdag 25 maart

- pages/index.vue
Wanneer deze PR wordt gemerged, dan is de disclaimer onder het formulier weggehaald en verplaatst naar een pop-up.
> Verplaats de disclaimer naar een pop-up tekst

- components/NeedHelpForm.vue
Wanneer deze PR wordt gemerged, dan is het duidelijker dat de bij het hulp aanvragen voor een ander de gegevens van de ander niet perse benodigd zijn.
> Hulptekst toegevoegd aan het formulier, zodat duidelijk is dat niet alles verplicht is om in te vullen

- pages/hulp-bieden.vue
- pages/index.vue
- pages/veelgestelde-vragen.vue
Wanneer deze PR wordt gemerged, is de website verrijkt met een telefoonnummer en website voor meer informatie over het coronavirus.
> Nieuwe teksten toevoegen over het coronavirus

- pages/index.vue
Wanneer deze PR wordt gemerged, ...
...
> Nal 121 socialposts op homepage en vervolgpagina

- pages/index.vue
Wanneer deze PR wordt gemerged, ...
...
> add grey background to social wall

- pages/verhalen.vue
Wanneer deze PR wordt gemerged, ...
...
> visually improve /verhalen page

- components/FooterContent.vue
- pages/hulp-bieden.vue
- pages/index.vue
- pages/veelgestelde-vragen.vue
Wanneer deze PR wordt gemerged, worden de kleine tesktuele wijzigingen voor donderdag 26 maart doorgevoerd
Klik op het linkje: https://deploy-preview-52--nietalleen.netlify.com/
> NAL-119: Kleine tekstuele wijzigingen donderdag 26 maart

- layouts/default.vue
Wanneer deze PR wordt gemerged, dan worden de CCM waardes altijd uitgelezen. ook als de ccm al klaar is.
check of de google maps kaart werkt in bijvoorbeeld Safari, blijf refreshen, probeer hem stuk te maken totdat hij zegt dat je je cookie voorkeuren nog niet hebt opgegeven.
> BUG: CCM is soms al geladen, voordat de layout wordt gemount

- components/FooterContent.vue
- components/HelpersMap.vue
- pages/over.vue
- pages/tv-programma.vue
Wanneer deze PR wordt gemerged, zijn er wat teksten geupdatet.
> NAL-138: tekstuele aanpassingen 27 maart

- pages/hulp-bieden.vue
- pages/over.vue
Wanneer deze PR wordt gemerged, zijn de wijzingen van NAL-144 doorgevoerd.
> NAL-144: tekstuele wijzigingen 31 maart

- components/FooterContent.vue
- components/NeedHelpForm.vue
- layouts/default.vue
- pages/index.vue
Wanneer deze PR wordt gemerged, dan komen er wat tekstuele wijzigingen
> Tekstuele wijzigingen

- pages/over.vue
2 kleine dingetjes voor de website:
**Webpagina: https://nietalleen.nl/over**
- Graag toevoegen op alfabetische plek in lijst landelijke organisaties: Business as Mission
- Graag iets meer ruimte tussen lijst landelijke organisaties en “#Nietalleen wordt mede mogelijk gemaakt door”
> Tekstuele aanpassingen - woensdag 15 april

- pages/over.vue
Wanneer deze PR wordt gemerged, worden de teskstuele wijzigingen in productie genomen.
> HOME-108 - Kleine tekstuele wijzigingen Donderdag 23 april

- pages/index.vue
Wanneer deze PR wordt gemerged, .
...
> Changed opening times.

- pages/index.vue
Wanneer deze PR wordt gemerged, wordt de counter op de homepage bijgewerkt naar 1630.
> [Changed] Updated counter

- components/FooterContent.vue
- pages/hulp-bieden.vue
- pages/index.vue
Wanneer deze PR wordt gemerged, gaan er wat tekstuele wijzigingen "live"
Klik hieronder op het linkje ergens als ie klaar is met bouwen ;-) 
Hier dus: https://deploy-preview-83--nietalleen.netlify.app/
> Change texts.

- pages/doneren.vue
- pages/tv-programma.vue
- pages/veelgestelde-vragen.vue
Wanneer deze PR wordt gemerged, zullen de teksten erop gericht zijn Nietalleen voor de lange termijn bestemd te maken, in lijn met de informatie die hierover morgen wordt gepubliceerd.
> CORP-261: update texts for the new long term purpose of the Nietalleen platform

- pages/over.vue
Wanneer deze PR wordt gemerged, worden er twee hulpverleningsorganisaties toegevoegd aan de ove-pagina
Als 'ie klaar is met bouwen, hieronder ergens even op de preview-omgeving koekeloeren.
Deze dus: https://deploy-preview-92--nietalleen.netlify.app/over
> Add two organizations to the about-page.

- pages/over.vue
Wanneer deze PR wordt gemerged, is er weer een nieuwe organisatie toegevoegd aan de hulporganisaties.
klik, als de build klaar is,  klik op dit linkje: https://deploy-preview-93--nietalleen.netlify.app/over
Kijk of je "Youth with a mission" zit staan.
> Adds new helping organization.
